name-template: 'ğŸš€ v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸ’¡ Features'
    labels:
      - 'ğŸŒˆ Feature'
  - title: 'ğŸ› Bug fixes'
    labels:
      - 'âš ï¸ Bug'
  - title: 'ğŸ¤¯ Inner Changes'
    labels:
      - 'ğŸ“¦ Chore'
      - 'ğŸ“ƒ Docs'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## ğŸš€ What has changed in this version?
  ---
  $CHANGES
no-changes-template: 'No changes.'